import { NextRequest, NextResponse } from "next/server";
import { getUserFromRequest } from "@/lib/auth/session";
import { db } from "@/lib/db";

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  const user = await getUserFromRequest(req);
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const docId = params.id;
  const document = db.getDocumentById(docId, user.userId);
  if (!document) {
    return NextResponse.json({ error: "Document not found" }, { status: 404 });
  }

  const prepKit = db.getPrepKit(docId, user.userId);
  const summary = db.getSummaryByDocumentId(docId);
  const clauses = db.getClausesByDocumentId(docId);
  const obligations = db.getObligationsByDocumentId(docId);

  const format = req.nextUrl.searchParams.get("format") || "markdown";

  if (format === "markdown") {
    let md = `# LEGAL CONSULTATION PREPARATION REPORT
**Platform:** JurisPrism Legal Intelligence
**Document:** ${document.originalName} (${summary?.documentType || document.documentType})
**Date Generated:** ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
**Governing Law:** ${summary?.governingLaw || "Not specified"}

---

> **IMPORTANT LEGAL NOTICE:** This preparation report is generated by JurisPrism for informational purposes to prepare for a consultation with a licensed attorney. It does NOT constitute legal advice or formal representation.

---

## 1. What This Document Is About
${prepKit?.sections.aboutDocument || summary?.executiveSummary || "Document analysis summary."}

## 2. What You Are Agreeing To
${prepKit?.sections.whatIAmAgreeingTo?.map((item) => `- ${item}`).join("\n") || "Standard commitments."}

## 3. Key Obligations & Mandatory Commitments
${obligations?.map((o) => `### ${o.eventName}
- **Deadline / Window:** ${o.deadlineRaw}
- **Required Action:** ${o.requiredAction}
- **Governing Clause:** ${o.relevantClause}
- **Attention Level:** ${o.severity}
`).join("\n")}

## 4. Potential Areas of Concern (Legal Attention Map)
${clauses?.filter((c) => c.attentionLevel === "HIGH" || c.attentionLevel === "MEDIUM").map((c) => `### [${c.attentionLevel}] ${c.title} (${c.sectionNumber || "Clause"})
- **Original Excerpt:** "${c.originalText}"
- **Plain-English Impact:** ${c.plainExplanation}
- **Why Review With Counsel:** ${c.potentialConcern}
- **Suggested Question for Attorney:** ${c.suggestedQuestion}
`).join("\n")}

## 5. Prioritized Questions to Ask Your Lawyer
${prepKit?.sections.questionsForMyLawyer?.map((q, idx) => `${idx + 1}. **[${q.priority} PRIORITY]** ${q.question}\n   *Rationale:* ${q.reason}`).join("\n\n")}

## 6. Information & Documents to Gather Before Consultation
${prepKit?.sections.documentsAndInfoToGather?.map((d) => `- [ ] ${d}`).join("\n")}

## 7. Clarifications to Negotiate Before Signing
${prepKit?.sections.preSigningNegotiationPoints?.map((p) => `- [ ] ${p}`).join("\n")}

---
*Report compiled via JurisPrism AI Legal Intelligence Engine.*
`;

    return new NextResponse(md, {
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
        "Content-Disposition": `attachment; filename="JurisPrism_PrepKit_${document.id}.md"`,
      },
    });
  }

  return NextResponse.json({
    document,
    summary,
    prepKit,
    obligations,
    clauses,
  });
}
